[package]
name = "duocards-downloader"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
genanki-rs = "0.4"
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["json"] }
serde_json = "*"
